
#**Задание на повторение материала
###Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [2]:
import numpy as np
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

###Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [4]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [7]:
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [8]:
a.reshape(12, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

###Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [9]:
a.reshape(-1, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [10]:
a.reshape(-1, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [13]:
a.reshape(3, -1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
a.reshape(6, -1)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [28]:
a.reshape(12, -1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

###Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Ответ: нет

In [34]:
a.resize(12, 1) 
a.ndim

2

###Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [54]:
import random
b1 = np.random.randn(3, 4)
b1

array([[0.3229051 , 0.49394962, 0.3332098 , 0.95382205],
       [0.28677404, 0.21704658, 0.73915735, 0.93781833],
       [0.20109101, 0.16568639, 0.12101053, 0.27568564]])

In [55]:
b2 = b1.ravel()
b2

array([0.3229051 , 0.49394962, 0.3332098 , 0.95382205, 0.28677404,
       0.21704658, 0.73915735, 0.93781833, 0.20109101, 0.16568639,
       0.12101053, 0.27568564])

In [56]:
b1.size

12

In [57]:
b2.size

12

###Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [59]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

###Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?



In [61]:
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [66]:
np.allclose(a, b)


True

####Ответ: разницы нет

###Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [74]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [75]:
b =np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [77]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [78]:
v.size

10

###Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [80]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [81]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [83]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [140]:
B = A @ At
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [87]:
B.size

16

In [92]:
B_inv = np.linalg.inv(B)

LinAlgError: ignored

In [93]:
np.linalg.det(B)

0.0

####Ответ: Обратную матрицы для матрицы В вычислить невозможно, т.к. её определитель равен нулю



###Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [98]:
np.random.default_rng(seed = 42)

Generator(PCG64) at 0x7F840544FC80

###Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [108]:
c = np.random.randint(0, 16, 16)
c

array([11,  9,  5, 12, 11,  8,  0, 10, 10, 14,  9, 15, 11, 11, 15, 14])

###Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [109]:
C = c.reshape(4, 4)
C

array([[11,  9,  5, 12],
       [11,  8,  0, 10],
       [10, 14,  9, 15],
       [11, 11, 15, 14]])

In [110]:
D = B + C*10
D

array([[115, 104,  73, 152],
       [124, 130,  86, 222],
       [123, 226, 239, 362],
       [142, 232, 362, 442]])

In [111]:
np.linalg.det(D)

62650800.0

In [112]:
np.linalg.matrix_rank(D)

4

In [115]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.01886552, -0.00325327, -0.01147599,  0.00454519],
       [ 0.01683203, -0.02439777,  0.02559361, -0.01449559],
       [ 0.01273886, -0.01565599, -0.00270994,  0.00570208],
       [-0.02532897,  0.02667356, -0.00752744,  0.00374073]])

###Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [119]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.]])

In [141]:
E = np.where(D_inv == 0, C, B)
E


array([[  5,   9,   5,  32],
       [ 14,   8,  86,  10],
       [ 23,  14,   9, 212],
       [ 11, 122,  15, 302]])